# leyendo datos con múltiples parámetros

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Disponemos de un archivo en formato CSV, el cual se obtuvo de la página Información de Salud (TABNET) - DATASUS. Este archivo contiene los gastos hospitalarios públicos de cada una de las Unidades de la Federación Brasileña desde enero de 2008 hasta marzo de 2021.

Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:

1. Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.
2. La codificación del archivo es ISO-8859-1.
3. Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.
4. Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.
5. Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.

In [ ]:
import pandas as pd

In [ ]:
# datos = pd.read_csv('datos_sus.csv', sep=';')
'''
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-f0578de21933> in <cell line: 1>()
----> 1 datos = pd.read_csv('datos_sus.csv', sep=';')

10 frames
/usr/local/lib/python3.10/dist-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 56: invalid continuation byte
'''

"\n---------------------------------------------------------------------------\nUnicodeDecodeError                        Traceback (most recent call last)\n<ipython-input-2-f0578de21933> in <cell line: 1>()\n----> 1 datos = pd.read_csv('datos_sus.csv', sep=';')\n\n10 frames\n/usr/local/lib/python3.10/dist-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()\n\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 56: invalid continuation byte\n"

In [ ]:
import chardet

In [ ]:
with open('datos_sus.csv', 'rb')as file:
    print(chardet.detect(file.read()))

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [ ]:
# datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1')
'''
---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
<ipython-input-6-5dd9555235fd> in <cell line: 1>()
----> 1 datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1')

9 frames
/usr/local/lib/python3.10/dist-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 161
'''

"\n---------------------------------------------------------------------------\nParserError                               Traceback (most recent call last)\n<ipython-input-6-5dd9555235fd> in <cell line: 1>()\n----> 1 datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1')\n\n9 frames\n/usr/local/lib/python3.10/dist-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()\n\nParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 161\n"

In [ ]:
datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter = 9)
datos.head()
'''
<ipython-input-8-83ca80276e4e>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter = 9)
'''

<ipython-input-15-aca41ac087ee>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter = 9)

"\n<ipython-input-8-83ca80276e4e>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.\n  datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter = 9)\n"

In [ ]:
datos = pd.read_csv('datos_sus.csv', sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter = 9, engine='python')
datos.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

# Desafío: leyendo datos de otro link

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Tenemos un link de Google Sheets que contiene datos importantes sobre las emisiones de dióxido de carbono en todo el mundo. El conjunto de datos se obtuvo de Kaggle y consta de las emisiones de CO2 per cápita de todos los países del mundo entre 1990 y 2019.

En este desafío, tu función es leer este link de Google Sheets y luego guardar el DataFrame obtenido en formato CSV. ¿Listo para comenzar?

In [ ]:
import pandas as pd

sheet_id = '1clj6rGaGlvZaLto2lgfFA7lodefC0OJgC86WgDm1nMU'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'
datos = pd.read_csv(url)
datos

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),"191,745,115","167,681,579","95,957,742","8,472,111","75,545,827","68,467,956",...,"29,650,624","259,295,334","18,562,366","146,235,617","172,896,741","149,789,334","131,694,556","1,632,953","159,824,372","159,824,372"
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),"553,661,955","544,538,649","543,557,223","70,898,423","836,804,405","912,141,485",...,"985,522,312","950,695,879","1,036,293,852","1,099,779,111","113,504,405","1,031,811,348","81,330,073","777,674,934","792,137,069","792,137,069"
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),"1,819,541,634","124,281,022","683,699,826","638,307,036","645,355,189","605,436,253",...,"166,942,319","150,324,046","1,533,630,039","1,668,337,371","160,377,515","1,557,664,358","1,788,786,074","1,782,738,948","169,224,832","169,224,832"
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),"7,521,831,658","723,537,924","69,630,787","6,724,177,518","6,541,578,914","6,733,479,486",...,"5,850,886,105","5,944,654,173","5,942,800,412","5,807,127,723","6,026,181,822","6,080,600,282","6,104,133,912","6,362,975,399","6,481,217,432","6,481,217,432"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Samoa,WSM,East Asia & Pacific,CO2 emissions (metric tons per capita),"55,283,574","609,756,098","604,266,119","658,221,486","592,806,881","705,674,802",...,"1,066,843,067","1,057,703,002","1,048,701,723","1,092,498,145","1,240,245,954","1,542,099,372","1,586,830,344","1,478,626,161","1,522,124,134","1,522,124,134"
211,"Yemen, Rep.",YEM,Middle East & North Africa,CO2 emissions (metric tons per capita),"56,703,735","690,937,429","704,793,064","627,104,927","653,255,714","706,080,534",...,"963,978,488","858,490,955","1,106,687,715","1,062,211,282","511,361,652","399,363,829","359,621,635","341,068,402","380,633,361","380,633,361"
212,South Africa,ZAF,Sub-Saharan Africa,CO2 emissions (metric tons per capita),"6,729,798,587","6,424,621,766","6,175,429,944","6,219,193,872","6,215,847,077","6,378,789,568",...,"7,869,815,906","8,077,957,969","8,138,264,312","8,212,241,156","7,669,937,662","7,563,739,495","7,641,675,086","7,515,678,605","7,507,736,092","7,507,736,092"
213,Zambia,ZMB,Sub-Saharan Africa,CO2 emissions (metric tons per capita),"340,929,635","349,232,211","33,722,439","289,956,061","241,269,619","234,153,214",...,"217,496,732","27,860,069","284,057,568","304,549,552","312,354,964","325,114,844","404,067,778","445,489,133","380,717,051","380,717,051"
214,Zimbabwe,ZWE,Sub-Saharan Africa,CO2 emissions (metric tons per capita),"1,585,443,976","1,713,321,439","1,694,415,977","1,539,740,958","1,417,186,242","135,661,892",...,"88,488,553","915,734,944","919,824,123","889,104,126","899,769,991","78,544,084","726,297,071","857,411,269","80,297,852","80,297,852"

In [ ]:
datos.to_csv('datos_emisiones_co2.csv', index=False)

# Desafío: normalizar el JSON obtenido de la API

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase. El DataFrame que se muestra a continuación se generó después de obtener los datos de la API de Fruitvice:
```
index	genus	name	id	family	order	nutritions
0	Malus	Apple	6	Rosaceae	Rosales	{'carbohydrates': 11.4, 'protein': 0.3, 'fat': 0.4, 'calories': 52, 'sugar': 10.3}
1	Prunus	Apricot	35	Rosaceae	Rosales	{'carbohydrates': 3.9, 'protein': 0.5, 'fat': 0.1, 'calories': 15, 'sugar': 3.2}
2	Persea	Avocado	84	Lauraceae	Laurales	{'carbohydrates': 8.53, 'protein': 2, 'fat': 14.66, 'calories': 160, 'sugar': 0.66}
3	Musa	Banana	1	Musaceae	Zingiberales	{'carbohydrates': 22, 'protein': 1, 'fat': 0.2, 'calories': 96, 'sugar': 17.2}
4	Rubus	Blackberry 64	Rosaceae	Rosales	{'carbohydrates': 9, 'protein': 1.3, 'fat': 0.4, 'calories': 40, 'sugar': 4.5}
5	Fragaria	Blueberry	33	Rosaceae	Rosales	{'carbohydrates': 5.5, 'protein': 0, 'fat': 0.4, 'calories': 29, 'sugar': 5.4}
6	Prunus	Cherry	9	Rosaceae	Rosales	{'carbohydrates': 12, 'protein': 1, 'fat': 0.3, 'calories': 50, 'sugar': 8}
```
Este DataFrame tiene 6 columnas: genus (género), name (nombre), id, family (familia), order (orden) e nutritions (nutriciones). Observe que la columna nutritions tiene toda la información nutricional anidada en ella. Por tanto, es necesario normalizar los datos.

El desafío ahora es normalizar este DataFrame.

In [ ]:
import requests
import json

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')
resultado = json.loads(datos_frutas.text)

In [ ]:
import pandas as pd
datos_frutas_normalizado = pd.json_normalize(resultado)
datos_frutas_normalizado

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

# Desafío: leer una tabla de una página web

Es el momento de poner a prueba los conocimientos desarrollados durante la clase.

Vanessa es una científica de datos que está haciendo algunos análisis con datos ambientales. Está desarrollando un proyecto para evaluar el impacto ambiental de las actividades humanas en diferentes países del mundo, pero para ello necesita estimaciones de población de esos países. Al buscar en Internet, encontró una tabla de estimaciones de población en un artículo de la página de Wikipedia.

Al igual que Vanessa, tu desafío es obtener un DataFrame de la tabla que contiene la información del número de habitantes de cada país.


```
https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n
```

In [2]:
import pandas as pd

In [5]:
url = 'https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n'
datos = pd.read_html(url)[0]

In [6]:
datos

,N.º,País (o territorio dependiente),Proyección exponencial de la población al 1/1/2024[7]​,Total mun- dial (%),Cambio medio anual (%)[8]​,Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción[9]​,"Censo más reciente, última estimación oficial, proyección de la ONU o reloj de población nacional",Fecha de esta última cifra de población en particular (d/mm/aaaa)[10]​,Tipo[11]​,Enlace o hipervínculo (usualmente de tipo oficial) de esta última cifra de población
0,1,China[12]​,1 409 664 000,1768,-015,-2 078 000,-,-,1 409 670 000,31/12/2023,E,www.stats.gov.cn
1,2,India,1 399 361 000,1755,060,8 440 000,1048,115,1 400 744 000,1/03/2024,A,main.mohfw.gov.in
2,3,Estados Unidos,335 893 000,421,052,1 745 000,217,134,336 181 000,17/03/2024,R,www.census.gov
3,4,Indonesia,285 991 000,359,172,4 917 000,611,41,271 350 000,12/2020,E,www.bps.go.id
4,5,Pakistán,246 675 000,309,256,6 323 000,785,27,241 499 431,1/03/2023,C,www.pbs.gov.pk
...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Islas Cocos (Australia),600,000,174,0,000,40,593,11/08/2021,C,www.citypopulation.de
242,243,Islas Ultramarinas Menores de los Estados Unidos,100,000,-496,0,000,-,190,1/04/2010,C,www.statoids.com
243,244,Islas Pitcairn (RU),50,000,-041,0,000,-,47,1/07/2021,E,www.visitpitcairn.pn
244,NaN,Mundo,7 972 094 000,10000,100,80 521 000,10000,70,8 097 748 000,17/03/2024,R,www.worldometers.info
245,N°,País (o territorio dependiente),Proyección exponencial de la población al 1/1/...,Total mun- dial (%),Cambio medio anual (%),Cambio absoluto anual promedio,Cambio medio abs. total anual (%),Años para even- tual du- pli- ca- ción,"Censo más reciente, última estimación oficial,...",Fecha de esta última cifra de población en par...,Tipo,Enlace o hipervínculo (usualmente de tipo ofic...

# Desafío: manipulando una base de datos

Es el momento de poner a prueba tus conocimientos adquiridos durante la clase.

Usted es responsable de crear una base de datos local de clientes para una institución financiera. Disponemos del archivo CSV con los datos de los clientes.

Tu misión es:

1. Crear la base de datos local con la biblioteca SQLAlchemy.
2. Escribir los datos del archivo CSV en esta base de datos local.
3. Realizar tres actualizaciones en la base de datos:
    + Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.
    + Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.
    + Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:
        + ID_cliente: 6850985
        + Edad: 33
        + Grado_estudio: Doctorado
        + Estado_civil: Soltero
        + Tamaño_familia: 1
        + Categoria_de_renta: Empleado
        + Ocupacion: TI
        + Años_empleado: 2
        + Rendimiento_anual: 290000
        + Tiene_carro: 0
        + Vivienda: Casa/Departamento propio

Consejo importante: Para agregar un nuevo cliente a la tabla, use la cláusula INSERT INTO seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula VALUES y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

In [1]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

In [2]:
import pandas as pd
archivo = 'clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

42627

In [3]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
42622,5118156,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42623,5118157,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42624,5118158,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42625,5118159,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42626,5118160,44,Nivel super,None,NaN,None,None,NaN,NaN,NaN,None

In [4]:
# Actualizar
from sqlalchemy.exc import SQLAlchemyError
query = 'UPDATE clientes SET Rendimiento_anual=300000.0 WHERE ID_Cliente=6840104'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  0

In [5]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
42622,5118156,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42623,5118157,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42624,5118158,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42625,5118159,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42626,5118160,44,Nivel super,None,NaN,None,None,NaN,NaN,NaN,None

In [6]:
# Eliminar
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1

In [7]:
# Insertar
from sqlalchemy.exc import SQLAlchemyError
query = 'INSERT INTO clientes (ID_Cliente, Edad, Grado_estudio, Estado_civil, ' \
        'Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, ' \
        'Rendimiento_anual, Tiene_carro, Vivienda) ' \
        'VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", ' \
        '2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros insertados: ",r_set.rowcount)

#Registros insertados:  1

In [8]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
42622,5118157,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42623,5118158,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42624,5118159,44,Nivel superior,Casado,3.0,Empleado,Otro,5.0,202500.0,0.0,Casa/Departamento propio
42625,5118160,44,Nivel super,None,NaN,None,None,NaN,NaN,NaN,None
42626,6850985,33,Doctorado,Soltero,1.0,Empleado,TI,2.0,290000.0,0.0,Casa/Departamento propio